/*
 * $Id$
 *
 * Copyright (c) 2009 T-Systems International GmbH.
 * All rights reserved.
 * This software is the confidential and proprietary information
 * of T-Systems International GmbH.
 *
 */
package com.tsi.netbeans.modules.languages.velocity.parser;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.VelocityParser;
import org.netbeans.modules.parsing.api.Snapshot;
import org.netbeans.modules.parsing.spi.ParseException;
import org.netbeans.modules.parsing.spi.Parser.Result;

/**
 * Represents result of parsing created for one specific {@link
 * VTLSyntaxErrorsHighlightingTask}.
 *
 * @author <a href="mailto:werner.jaeger@t-systems.com">Werner Jaeger</a>
 */
public class VTLParserResult extends Result
{
   private final VelocityParser m_Parser;

   private boolean m_fValid;

   /**
    * Creates new {@code VTLParserResult} for the given snapshot.
    *
    * @param snapshot part of text to parse.
    * @param parser the actual parser generated by JavaCC.
    */
   VTLParserResult(final Snapshot snapshot, final VelocityParser parser)
   {
      super(snapshot);

      m_Parser = parser;
      m_fValid = true;
   }

   /**
    * Retrieves the actual parser instance.
    *
    * @return a reference to th parser instance actually use for parsing.
    *
    * @throws ParseException if this instance was {@link
    *         VTLParserResult#invalidate() invalidated}.
    */
   public VelocityParser getParser() throws ParseException
   {
      if (!m_fValid)
         throw new ParseException();

      return(m_Parser);
   }

   /**
    * {@inheritDoc}
    */
   @Override protected void invalidate()
   {
      m_fValid = false;
   }
}
