/* Generated By:JJTree: Do not edit this line. ASTDirective.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTDirective extends SimpleNode {
  public ASTDirective(int id) {
    super(id);
  }

  public ASTDirective(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c15ec384e72960d0a5cbd9c667cd5c3c (do not edit this line) */
