/* Generated By:JJTree: Do not edit this line. ASTMap.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTMap extends SimpleNode {
  public ASTMap(int id) {
    super(id);
  }

  public ASTMap(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4694240bf9f3b20e3d2d1d091ca403e9 (do not edit this line) */
