/* Generated By:JJTree: Do not edit this line. ASTStop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTStop extends SimpleNode {
  public ASTStop(int id) {
    super(id);
  }

  public ASTStop(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=059952cfb0835a539dc474b035e2de1b (do not edit this line) */
