/* Generated By:JJTree: Do not edit this line. ASTElseIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTElseIfStatement extends SimpleNode {
  public ASTElseIfStatement(int id) {
    super(id);
  }

  public ASTElseIfStatement(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=124dc20bf30dd93c1553189e5cd41625 (do not edit this line) */
