/* Generated By:JJTree: Do not edit this line. ASTModNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTModNode extends SimpleNode {
  public ASTModNode(int id) {
    super(id);
  }

  public ASTModNode(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=768387f3d46665aee323a60488a605d2 (do not edit this line) */
