/* Generated By:JJTree: Do not edit this line. ASTNotNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTNotNode extends SimpleNode {
  public ASTNotNode(int id) {
    super(id);
  }

  public ASTNotNode(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a4711946db6f94af0d446e6eca0949f6 (do not edit this line) */
