/* Generated By:JJTree: Do not edit this line. ASTReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTReference extends SimpleNode {
  public ASTReference(int id) {
    super(id);
  }

  public ASTReference(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de76d827a7bb8cdf8e0666cbd55f5989 (do not edit this line) */
