/* Generated By:JavaCC: Do not edit this line. VelocityParserTreeConstants.java Version 5.0 */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public interface VelocityParserTreeConstants
{
  public int JJTPROCESS = 0;
  public int JJTVOID = 1;
  public int JJTESCAPEDDIRECTIVE = 2;
  public int JJTESCAPE = 3;
  public int JJTCOMMENT = 4;
  public int JJTUNPARSEDCONTENT = 5;
  public int JJTFLOATINGPOINTLITERAL = 6;
  public int JJTINTEGERLITERAL = 7;
  public int JJTSTRINGLITERAL = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTWORD = 10;
  public int JJTDIRECTIVE = 11;
  public int JJTBLOCK = 12;
  public int JJTMAP = 13;
  public int JJTOBJECTARRAY = 14;
  public int JJTINTEGERRANGE = 15;
  public int JJTMETHOD = 16;
  public int JJTREFERENCE = 17;
  public int JJTTRUE = 18;
  public int JJTFALSE = 19;
  public int JJTTEXT = 20;
  public int JJTFOREACHSTATEMENT = 21;
  public int JJTMACROSTATEMENT = 22;
  public int JJTINCLUDESTATEMENT = 23;
  public int JJTIFSTATEMENT = 24;
  public int JJTELSESTATEMENT = 25;
  public int JJTELSEIFSTATEMENT = 26;
  public int JJTSETDIRECTIVE = 27;
  public int JJTSTOP = 28;
  public int JJTEXPRESSION = 29;
  public int JJTASSIGNMENT = 30;
  public int JJTORNODE = 31;
  public int JJTANDNODE = 32;
  public int JJTEQNODE = 33;
  public int JJTNENODE = 34;
  public int JJTLTNODE = 35;
  public int JJTGTNODE = 36;
  public int JJTLENODE = 37;
  public int JJTGENODE = 38;
  public int JJTADDNODE = 39;
  public int JJTSUBTRACTNODE = 40;
  public int JJTMULNODE = 41;
  public int JJTDIVNODE = 42;
  public int JJTMODNODE = 43;
  public int JJTNOTNODE = 44;


  public String[] jjtNodeName = {
    "process",
    "void",
    "EscapedDirective",
    "Escape",
    "Comment",
    "UnparsedContent",
    "FloatingPointLiteral",
    "IntegerLiteral",
    "StringLiteral",
    "Identifier",
    "Word",
    "Directive",
    "Block",
    "Map",
    "ObjectArray",
    "IntegerRange",
    "Method",
    "Reference",
    "True",
    "False",
    "Text",
    "ForEachStatement",
    "MacroStatement",
    "IncludeStatement",
    "IfStatement",
    "ElseStatement",
    "ElseIfStatement",
    "SetDirective",
    "Stop",
    "Expression",
    "Assignment",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NotNode",
  };
}
/* JavaCC - OriginalChecksum=ec33be0c33a2591df3b08da5a52dc4cb (do not edit this line) */
