/* Generated By:JJTree: Do not edit this line. ASTInnerIntegerRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTInnerIntegerRange extends SimpleNode {
  public ASTInnerIntegerRange(int id) {
    super(id);
  }

  public ASTInnerIntegerRange(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c96e6b98fc7ec66da377f3520bc4579 (do not edit this line) */
