/* Generated By:JavaCC: Do not edit this line. VelocityParserTreeConstants.java Version 5.0 */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public interface VelocityParserTreeConstants
{
  public int JJTPROCESS = 0;
  public int JJTVOID = 1;
  public int JJTESCAPEDDIRECTIVE = 2;
  public int JJTESCAPE = 3;
  public int JJTCOMMENT = 4;
  public int JJTFLOATINGPOINTLITERAL = 5;
  public int JJTINTEGERLITERAL = 6;
  public int JJTSTRINGLITERAL = 7;
  public int JJTIDENTIFIER = 8;
  public int JJTWORD = 9;
  public int JJTDIRECTIVE = 10;
  public int JJTBLOCK = 11;
  public int JJTMAP = 12;
  public int JJTOBJECTARRAY = 13;
  public int JJTINTEGERRANGE = 14;
  public int JJTMETHOD = 15;
  public int JJTREFERENCE = 16;
  public int JJTTRUE = 17;
  public int JJTFALSE = 18;
  public int JJTTEXT = 19;
  public int JJTFOREACHSTATEMENT = 20;
  public int JJTMACROSTATEMENT = 21;
  public int JJTINCLUDESTATEMENT = 22;
  public int JJTIFSTATEMENT = 23;
  public int JJTELSESTATEMENT = 24;
  public int JJTELSEIFSTATEMENT = 25;
  public int JJTSETDIRECTIVE = 26;
  public int JJTSTOP = 27;
  public int JJTEXPRESSION = 28;
  public int JJTASSIGNMENT = 29;
  public int JJTORNODE = 30;
  public int JJTANDNODE = 31;
  public int JJTEQNODE = 32;
  public int JJTNENODE = 33;
  public int JJTLTNODE = 34;
  public int JJTGTNODE = 35;
  public int JJTLENODE = 36;
  public int JJTGENODE = 37;
  public int JJTADDNODE = 38;
  public int JJTSUBTRACTNODE = 39;
  public int JJTMULNODE = 40;
  public int JJTDIVNODE = 41;
  public int JJTMODNODE = 42;
  public int JJTNOTNODE = 43;


  public String[] jjtNodeName = {
    "process",
    "void",
    "EscapedDirective",
    "Escape",
    "Comment",
    "FloatingPointLiteral",
    "IntegerLiteral",
    "StringLiteral",
    "Identifier",
    "Word",
    "Directive",
    "Block",
    "Map",
    "ObjectArray",
    "IntegerRange",
    "Method",
    "Reference",
    "True",
    "False",
    "Text",
    "ForEachStatement",
    "MacroStatement",
    "IncludeStatement",
    "IfStatement",
    "ElseStatement",
    "ElseIfStatement",
    "SetDirective",
    "Stop",
    "Expression",
    "Assignment",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NotNode",
  };
}
/* JavaCC - OriginalChecksum=5694557666472b152dfaedae87af9239 (do not edit this line) */
