/* Generated By:JJTree: Do not edit this line. ASTInnerObjectArray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTInnerObjectArray extends SimpleNode {
  public ASTInnerObjectArray(int id) {
    super(id);
  }

  public ASTInnerObjectArray(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=15fdb6c08dfa8a7483cef0bca6c55ce0 (do not edit this line) */
