/* Generated By:JJTree: Do not edit this line. ASTComment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTComment extends SimpleNode {
  public ASTComment(int id) {
    super(id);
  }

  public ASTComment(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8250cb728cf87917420c6048e8bcf4dc (do not edit this line) */
