/* Generated By:JJTree: Do not edit this line. ASTEscapedDirective.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTEscapedDirective extends SimpleNode {
  public ASTEscapedDirective(int id) {
    super(id);
  }

  public ASTEscapedDirective(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebd663ca1ce9eb026a17f68ec77dd104 (do not edit this line) */
