/* Generated By:JJTree: Do not edit this line. ASTEscape.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTEscape extends SimpleNode {
  public ASTEscape(int id) {
    super(id);
  }

  public ASTEscape(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30d95bbe585efd145e8668b6e68c4400 (do not edit this line) */
