/* Generated By:JJTree: Do not edit this line. ASTForEachStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTForEachStatement extends SimpleNode {
  public ASTForEachStatement(int id) {
    super(id);
  }

  public ASTForEachStatement(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f254a841998ba29d409935bfd4679d01 (do not edit this line) */
