/* Generated By:JJTree: Do not edit this line. ASTIntegerRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTIntegerRange extends SimpleNode {
  public ASTIntegerRange(int id) {
    super(id);
  }

  public ASTIntegerRange(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c69c690638b17b03d9578bfb206c12b2 (do not edit this line) */
