/* Generated By:JJTree: Do not edit this line. ASTObjectArray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTObjectArray extends SimpleNode {
  public ASTObjectArray(int id) {
    super(id);
  }

  public ASTObjectArray(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b315729652ba13cbbc23ee9d7e97629c (do not edit this line) */
