/* Generated By:JJTree: Do not edit this line. ASTprocess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTprocess extends SimpleNode {
  public ASTprocess(int id) {
    super(id);
  }

  public ASTprocess(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c690596aa16f6af3bd6e3cc00f7120e6 (do not edit this line) */
