/* Generated By:JJTree: Do not edit this line. ASTSetDirective.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTSetDirective extends SimpleNode {
  public ASTSetDirective(int id) {
    super(id);
  }

  public ASTSetDirective(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6235a9f809428be339056dcabc14d6d5 (do not edit this line) */
