/* Generated By:JJTree: Do not edit this line. ASTWord.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tsi.netbeans.modules.languages.velocity.jcclexer.node;

import com.tsi.netbeans.modules.languages.velocity.jcclexer.*;

public
class ASTWord extends SimpleNode {
  public ASTWord(int id) {
    super(id);
  }

  public ASTWord(VelocityParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2fb26ffb408a246f0e6892cf8ee5ee0b (do not edit this line) */
