/* Generated By:JJTree&JavaCC: Do not edit this line. VelocityParserConstants.java */
package com.tsi.netbeans.modules.languages.velocity.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VelocityParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACKET = 1;
  /** RegularExpression Id. */
  int RBRACKET = 2;
  /** RegularExpression Id. */
  int COMMA = 3;
  /** RegularExpression Id. */
  int DOUBLEDOT = 4;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int LEFT_CURLEY = 6;
  /** RegularExpression Id. */
  int RIGHT_CURLEY = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int WORD_IN = 10;
  /** RegularExpression Id. */
  int REFMOD2_RPAREN = 11;
  /** RegularExpression Id. */
  int ESCAPE_DIRECTIVE = 12;
  /** RegularExpression Id. */
  int SET_DIRECTIVE = 13;
  /** RegularExpression Id. */
  int DOLLAR = 14;
  /** RegularExpression Id. */
  int DOLLARBANG = 15;
  /** RegularExpression Id. */
  int HASH = 19;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT_START = 20;
  /** RegularExpression Id. */
  int DOUBLE_ESCAPE = 21;
  /** RegularExpression Id. */
  int ESCAPE = 22;
  /** RegularExpression Id. */
  int TEXT = 23;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 24;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 25;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 26;
  /** RegularExpression Id. */
  int UNPARSED_CONTENT = 27;
  /** RegularExpression Id. */
  int WHITESPACE = 29;
  /** RegularExpression Id. */
  int STRING_LITERAL = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int NEWLINE = 33;
  /** RegularExpression Id. */
  int MINUS = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int MULTIPLY = 36;
  /** RegularExpression Id. */
  int DIVIDE = 37;
  /** RegularExpression Id. */
  int MODULUS = 38;
  /** RegularExpression Id. */
  int BINARY_AND = 39;
  /** RegularExpression Id. */
  int BINARY_OR = 40;
  /** RegularExpression Id. */
  int LOGICAL_AND = 41;
  /** RegularExpression Id. */
  int LOGICAL_OR = 42;
  /** RegularExpression Id. */
  int LOGICAL_LT = 43;
  /** RegularExpression Id. */
  int LOGICAL_LE = 44;
  /** RegularExpression Id. */
  int LOGICAL_GT = 45;
  /** RegularExpression Id. */
  int LOGICAL_GE = 46;
  /** RegularExpression Id. */
  int LOGICAL_EQUALS = 47;
  /** RegularExpression Id. */
  int LOGICAL_NOT_EQUALS = 48;
  /** RegularExpression Id. */
  int LOGICAL_NOT = 49;
  /** RegularExpression Id. */
  int EQUALS = 50;
  /** RegularExpression Id. */
  int END = 51;
  /** RegularExpression Id. */
  int FOREACH_DIRECTIVE = 52;
  /** RegularExpression Id. */
  int MACRO_DIRECTIVE = 53;
  /** RegularExpression Id. */
  int INCLUDE_DIRECTIVE = 54;
  /** RegularExpression Id. */
  int IF_DIRECTIVE = 55;
  /** RegularExpression Id. */
  int ELSEIF_DIRECTIVE = 56;
  /** RegularExpression Id. */
  int ELSE_DIRECTIVE = 57;
  /** RegularExpression Id. */
  int STOP_DIRECTIVE = 58;
  /** RegularExpression Id. */
  int MACROCALL_DIRECTIVE = 59;
  /** RegularExpression Id. */
  int DIGIT = 60;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 61;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 62;
  /** RegularExpression Id. */
  int EXPONENT = 63;
  /** RegularExpression Id. */
  int LETTER = 64;
  /** RegularExpression Id. */
  int DIRECTIVE_CHAR = 65;
  /** RegularExpression Id. */
  int WORD = 66;
  /** RegularExpression Id. */
  int BRACKETED_WORD = 67;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 68;
  /** RegularExpression Id. */
  int ALPHANUM_CHAR = 69;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 70;
  /** RegularExpression Id. */
  int IDENTIFIER = 71;
  /** RegularExpression Id. */
  int DOT = 72;
  /** RegularExpression Id. */
  int LCURLY = 73;
  /** RegularExpression Id. */
  int RCURLY = 74;
  /** RegularExpression Id. */
  int REFERENCE_TERMINATOR = 75;
  /** RegularExpression Id. */
  int DIRECTIVE_TERMINATOR = 76;

  /** Lexical state. */
  int DIRECTIVE = 0;
  /** Lexical state. */
  int REFMOD2 = 1;
  /** Lexical state. */
  int REFMODIFIER = 2;
  /** Lexical state. */
  int DEFAULT = 3;
  /** Lexical state. */
  int REFERENCE = 4;
  /** Lexical state. */
  int PRE_DIRECTIVE = 5;
  /** Lexical state. */
  int IN_UNPARSED_CONTENT = 6;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 7;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 8;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 9;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"..\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "<RPAREN>",
    "\"in\"",
    "\")\"",
    "<ESCAPE_DIRECTIVE>",
    "<SET_DIRECTIVE>",
    "<DOLLAR>",
    "<DOLLARBANG>",
    "<token of kind 16>",
    "\"#*\"",
    "\"#[[\"",
    "<HASH>",
    "\"##\"",
    "\"\\\\\\\\\"",
    "\"\\\\\"",
    "<TEXT>",
    "<SINGLE_LINE_COMMENT>",
    "\"*#\"",
    "\"*#\"",
    "\"]]#\"",
    "<token of kind 28>",
    "<WHITESPACE>",
    "<STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<NEWLINE>",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<BINARY_AND>",
    "<BINARY_OR>",
    "<LOGICAL_AND>",
    "<LOGICAL_OR>",
    "<LOGICAL_LT>",
    "<LOGICAL_LE>",
    "<LOGICAL_GT>",
    "<LOGICAL_GE>",
    "<LOGICAL_EQUALS>",
    "<LOGICAL_NOT_EQUALS>",
    "<LOGICAL_NOT>",
    "\"=\"",
    "<END>",
    "<FOREACH_DIRECTIVE>",
    "<MACRO_DIRECTIVE>",
    "<INCLUDE_DIRECTIVE>",
    "<IF_DIRECTIVE>",
    "<ELSEIF_DIRECTIVE>",
    "<ELSE_DIRECTIVE>",
    "<STOP_DIRECTIVE>",
    "<MACROCALL_DIRECTIVE>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIRECTIVE_CHAR>",
    "<WORD>",
    "<BRACKETED_WORD>",
    "<ALPHA_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<DOT>",
    "\"{\"",
    "\"}\"",
    "<REFERENCE_TERMINATOR>",
    "<DIRECTIVE_TERMINATOR>",
  };

}
